server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rongxiaotong?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
  jackson:
    time-zone: GMT+8
file:
  location:
    directory: E:\learn\nginx-1.21.1\images
