server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rongxiaotong?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: root
  jackson:
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
#nginx存放图片的路径
file:
  location:
    directory: E:\learn\nginx-1.21.1\images
# 支付宝 appId,私钥，支付宝公钥
alipay:
  info:
    appId: 支付宝appid
    privateKey:  私钥
    alipayPublicKey: 支付宝公钥
